# https://taskfile.dev
version: '3'

includes:
  argocd: ./tasks/argocd.yaml
  docs: ./tasks/docs.yaml
  k8s: ./tasks/k8s.yaml
  python: ./tasks/python.yaml
  tofu: ./tasks/tofu.yaml

tasks:
  lint:
    cmds:
      - task: tofu:fmt:ci
      - task: python:pc:lint
      - task: python:lint

  fmt:
    cmds:
      - task: tofu:fmt
      - task: python:fmt

  lint:ci:
    cmds:
      - task: tofu:fmt:ci
      - task: python:pc:lint

  civo:bootstrap:
    cmds:
      - op run --env-file=".env" -- civo apikey save --load-from-env
