# https://taskfile.dev
version: '3'

tasks:
  k8s-bootstrap:
    cmds:
      - mkdir ~/.kube | true
      - op read op://lab/kubernetes_config/config > ~/.kube/config
      - kubectl context use-context lab

  lint:
    cmds:
      - task: tf-fmt
      - task: pc-lint

  lint-ci:
    cmds:
      - task: tf-fmt-ci
      - task: pc-lint

  pc-update:
    cmds:
      - task: python-install
      - poetry run pre-commit autoupdate

  pc-lint:
    cmds:
      - task: python-install
      - poetry run pre-commit run --all-files

  python-install:
    cmds:
      - poetry install --no-root

  docs-serve:
    cmds:
      - task: python-install
      - poetry run mkdocs serve

  docs-release:
    cmds:
      - task: python-install
      - poetry run mkdocs gh-deploy --force

  tf-fmt:
    cmds:
      - tofu fmt -recursive

  tf-fmt-ci:
    cmds:
      - tofu fmt -recursive -check
