argo-workflows:
  server:
    extraArgs:
      - --auth-mode=sso

    sso:
      issuer: https://argocd.aoach.tech/api/dex
      sessionExpiry: 240h
      clientId:
        name: argocd-secret
        key: dex.github.clientID
      clientSecret:
        name: argocd-secret
        key: dex.github.clientSecret
      redirectUrl: https://argo-workflows.aoach.tech/oauth2/callback
      rbac:
        enabled: false

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - argo-workflows.aoach.tech
