version: '3'

tasks:
  lint:
    desc: Lint Dockerfiles with Hadolint.
    cmds:
      - hadolint dockerfiles/**/Dockerfile

  build: &build
    desc: "Generic Docker build task."
    cmds:
      - docker buildx build --file {{.PATH}}/Dockerfile -t $(basename {{.PATH}}) {{.PATH}}
    internal: true
    vars:
      PATH: override_this

  run: &run
    desc: "Generic Docker run task."
    cmds:
      - task: build:{{base .PATH}}
      - docker run -it --entrypoint sh --rm --name $(basename {{.PATH}}) $(basename {{.PATH}})
    vars:
      PATH: override_this

  build:argocd_tools:
    <<: *build
    desc: "Build argocd_tools Dockerfile."
    internal: false
    vars:
      PATH: dockerfiles/argocd_tools

  run:argocd_tools:
    <<: *run
    desc: "Run argocd_tools Dockerfile."
    internal: false
    vars:
      PATH: dockerfiles/argocd_tools
