version: '3'



tasks:
  lint:
    desc: Lint Dockerfiles with Hadolint.
    cmds:
      - hadolint dockerfiles/**/Dockerfile

  build: &build
    desc: "Generic Docker build task."
    cmds:
      - docker buildx build --file {{.PATH}}/Dockerfile -t $(basename {{.PATH}}) {{.PATH}}
    internal: true
    vars:
      PATH: dockerfiles/diffs

  run: &run
    desc: "Generic Docker run task."
    cmds:
      - docker run -it --entrypoint sh --rm --name $(basename {{.PATH}}) $(basename {{.PATH}})
    vars:
      PATH: dockerfiles/diffs

  build:diff:
    <<: *build
    desc: "Build diffs Dockerfile."
    internal: false
    vars:
      PATH: dockerfiles/diffs

  run:diff:
    <<: *run
    desc: "Run diff Dockerfile."
    internal: false
    vars:
      PATH: dockerfiles/diffs
