version: '3'

tasks:
  images:
    desc: Generates diagrams.
    dir: ./docs/diagrams
    cmds:
      - poetry run python infrastructure.py
      - poetry run python tooling.py
      - poetry run python kubernetes.py

  serve:
    desc: Run mkdocs server locally.
    cmds:
      - poetry run mkdocs serve

  release:
    desc: Publish docs to Github Pages.
    cmds:
      - poetry install --no-root
      - poetry run mkdocs gh-deploy --force
