version: '3'

tasks:
  fmt:
    cmds:
      - tofu fmt -recursive

  fmt:ci:
    cmds:
      - tofu fmt -recursive -check

  plan:aoach:
    cmds:
      - op run --env-file=".env" -- spacectl stack preview --sha `git rev-parse HEAD` --id dns-aoach-tech -tail
