argo-cd:
  configs:
    secret:
      createSecret: false

  server:
    extraArgs:
      - --insecure

    config:
      url: https://argocd.aoach.tech
      admin.enabled: "false"
      accounts.GithubActions: apiKey
      dex.config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $dex.github.clientID
              clientSecret: $dex.github.clientSecret
              orgs:
              - name: HamsterHomelab
        staticClients:
          - id: argo-workflows-sso
            name: Argo Workflow
            redirectURIs:
              - https://argoworkflows.aoach.tech/oauth2/callback
            secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET

    rbacConfig:
      policy.csv: |
        g, GithubActions, role:readonly
        g, HamsterHomelab:admin, role:admin
        g, some-new-team:admin, role:admin

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hosts:
        - argocd.aoach.tech

  # dex:
  #   env:
  #     - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
  #       valueFrom:
  #         secretKeyRef:
  #           name: argo-workflows-sso
  #           key: client-secret
