---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: argocd-secret
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  itemPath: "vaults/lab/items/grafana"
