oauth2-proxy:
  config:
    existingSecret: github-oauth-homepage
    configFile: |-
      provider = "github"
      email_domains = [ "*" ]
      github_org = "HamsterHomelab"
      upstreams = [ "file:///dev/null" ]
      scope = "user:email"

  ingress:
    enabled: true
    className: nginx
    path: /oauth2
    pathType: Prefix
    hosts:
      - aoach.tech
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls:
      - hosts:
        - aoach.tech
