apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: flame-secret
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  itemPath: "vaults/lab/items/flame"
