apiVersion: apps/v1
kind: Deployment
metadata:
  name: discordirc
spec:
  selector:
    matchLabels:
      app: discordirc
  replicas: 1
  template:
    metadata:
      labels:
        app: discordirc
    spec:
      containers:
      - name: discordirc
        image: cluelesshamster86/docker-discordirc:latest
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        secret:
          secretName: discordirc
          items:
            - key: config
              path: config.json
