k8s-monitoring:
  cluster:
    name: lab

  externalServices:
    prometheus:
      hostKey: prometheus_host
      basicAuth:
        usernameKey: prometheus_username
        passwordKey: prometheus_password
      secret:
        create: false
        name: "grafana"
        namespace: "infrastructure"

    loki:
      hostKey: loki_host
      basicAuth:
        usernameKey: loki_username
        passwordKey: loki_password
      secret:
        create: false
        name: "grafana"
        namespace: "infrastructure"
  metrics:
    cost:
      enabled: false

  opencost:
    enabled: false
