---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: github-oauth-homepage
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  itemPath: "vaults/lab/items/oauth-proxy-homepage"
