apiVersion: apps/v1
kind: Deployment
metadata:
    name: ghost
    labels:
        app: ghost
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ghost
    template:
        metadata:
            labels:
                app: ghost
        spec:
            strategy:
              type: Recreate
            containers:
            - name: ghost
              image: ghost:5.79.3
              imagePullPolicy: Always
              ports:
                - containerPort: 2368
              env:
                - name: url
                  value: https://ivanlee.me
                - name: database__client
                  value: mysql
                - name: mail__transport
                  value: smtp
                - name: mail__options__service
                  value: mailgun
                - name: mail__options__auth__user
                  value: postmaster@mail.ivanlee.me
              envFrom:
                - secretRef:
                    name: ghost-secrets
                - secretRef:
                    name: ghost-mailgun-credentials
              tty: true
              volumeMounts:
              - mountPath: /var/lib/ghost/content
                name: content
            volumes:
            - name: content
              persistentVolumeClaim:
                claimName: ghost-pvc
