apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-tanka
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: tanka
    spec:
      version: v1.0
      init:
        command: [sh, -c]
        args:
          - |
            "jb install"
      generate:
        command: [sh, -c]
        args:
          - |
            tk show --dangerous-allow-redirect $PARAM_PATH
      discover:
        fileName: jsonnetfile.json
      parameters:
        static:
          - name: path
            title: Environment path
            tooltip: Folder containing tanka environment.
            required: true
            itemType: string
