apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rollouts-demo
  name: rollouts-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
