name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.6.1
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: "Lint"
        run: |
          pip install -U pip poetry
          task lint:ci
      - name: ArgoCD Diff
        uses: quizlet/argocd-diff-action@master
        with:
          argocd-server-url: argocd.aoach.tech
          argocd-token: ${{ secrets.ARGOCD_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          argocd-version: v2.9.5
          argocd-extra-cli-args: --grpc-web
