name: k8s-manifests

on:
  pull_request:
    paths:
    - kubernetes/applications/**
  # push:
  #   branches: argocd_diffs_in_prs

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed-folders: ${{steps.output-step.outputs.folders}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup main branch locally without switching current branch
        run: git fetch origin main:main
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
      # Credit to https://www.kenmuse.com/blog/dynamic-build-matrices-in-github-actions/
      - id: output-step
        name: Generate list of changed folders
        run: |
          TARGETS=$(git diff --name-only main -- kubernetes/applications | xargs -L1 dirname | uniq | jq -cRn '[inputs]')
          echo "folders=$(jq -cn --argjson environments "$TARGETS" '{folder: $environments}')" >> "$GITHUB_OUTPUT"

  run-matrix:
    needs: changes
    runs-on: ubuntu-latest
    container:
      image: cluelesshamster86/argocd_diff:argocd_diffs_in_prs
    strategy:
      matrix: ${{ fromJson(needs.changes.outputs.changed-folders) }}
    steps:
      - run: echo ${{matrix.folder}}
      - uses: actions/checkout@v4
      - run: |
          argocd app diff --grpc-web --server $ARGOCD_URL --auth-token $ARGOCD_JWT $(basename ${{matrix.folder}}) --refresh --revision $GITHUB_SHA
        env:
          ARGOCD_URL: ${{ secrets.ARGOCD_URL }}
          ARGOCD_JWT: ${{ secrets.ARGOCD_JWT }}
