name: k8s-manifests

on:
  pull_request:
    paths:
    - kubernetes/applications/**
  # push:
  #   branches: argocd_diffs_in_prs

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed-folders: ${{steps.output-step.outputs.folders}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup main branch locally without switching current branch
        run: git fetch origin main:main
      - name: 'Setup jq'
        uses: dcarbone/install-jq-action@v2
      # Credit to https://www.kenmuse.com/blog/dynamic-build-matrices-in-github-actions/
      - id: output-step
        name: Generate list of changed folders
        run: |
          TARGETS=$(git diff --name-only main -- kubernetes/applications | xargs -L1 dirname | uniq | jq -cRn '[inputs]')
          echo "folders=$(jq -cn --argjson environments "$TARGETS" '{folder: $environments}')" >> "$GITHUB_OUTPUT"

  run-matrix:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    container:
      image: cluelesshamster86/argocd_diff:argocd_diffs_in_prs@sha256:aece8eb5a03cd3f50e1aa838449d45dd8df06f55ea6cf06de2704c2cbe2b347b
    strategy:
      matrix: ${{ fromJson(needs.changes.outputs.changed-folders) }}
    steps:
      - uses: actions/checkout@v4
      - name: Get manifests
        run: |
          argocd app manifests --grpc-web --server $ARGOCD_URL --auth-token $ARGOCD_TOKEN $(basename ${{matrix.folder}}) --revision $GITHUB_SHA >> manifests.yaml
        env:
          ARGOCD_URL: ${{ secrets.ARGOCD_URL }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
      - name: Run Kubeconform.
        run: kubeconform manifests.yaml
      - name: Get ArgoCD diff
        id: diff
        continue-on-error: true
        run: |
          set +e
          argocd app diff --grpc-web --server $ARGOCD_URL --auth-token $ARGOCD_TOKEN $(basename ${{matrix.folder}}) --refresh --revision $GITHUB_SHA >> k8s.diff
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"
        env:
          ARGOCD_URL: ${{ secrets.ARGOCD_URL }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
      - name: Generate report
        run: gomplate -f /argocd_diff/diff.md.tmpl -o diff.md -d diff=k8s.diff?type=text/plain
        env:
          APPLICAITON_PATH: ${{matrix.folder}}
      - name: Post diff if exists
        if: steps.diff.outputs.exitcode == 1
        run: |
          cat diff.md | github-commenter \
            -token $GITHUB_TOKEN \
            -owner $GITHUB_REPOSITORY_OWNER \
            -repo $(basename $GITHUB_REPOSITORY) \
            -type pr \
            -number ${{github.event.pull_request.number}} \
            -edit-comment-regex "ArgoCD Diff Report - ${{matrix.folder}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail on CLI failure
        if: steps.diff.outputs.exitcode == 2
        run: exit 1
