name: Release docs

on:
  push:
    branches: ["main", "docs/*"]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Deploy docs
        run: |
          task docs-deploy